
name: MATLAB CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-java:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        # Setup job
        - name: Set up JDK 11 for x64
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            architecture: x64

        # Sets up MATLAB on the GitHub Actions runner
        - name: Setup MATLAB
          uses: matlab-actions/setup-matlab@v1
          with:
            release: R2024a

        - name: Testing
          run: |
            mkdir -p MATLAB/lib && \
            cp RJSDMX/inst/java/SDMX.jar MATLAB/lib && \
            cd MATLAB/ && \
            matlab -batch "addpath .;result=runtests('test/testSDMX.m');exit(any([result.Failed]));"
