name: MATLAB CI

on:
  workflow_run:
    workflows: ["JAVA CI"]
    types:
      - completed
    branches:
      - master
      - develop

permissions:
  contents: read
  actions: read

jobs:
  test-matlab:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository at triggering commit
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download SDMX JAR from JAVA CI
        uses: actions/download-artifact@v8.0.1
        with:
          name: SDMX.jar
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          path: MATLAB/files/lib

      - name: Download VERSION from JAVA CI
        uses: actions/download-artifact@v8.0.1
        with:
          name: VERSION
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          path: .

      - name: Apply VERSION
        run: |
          echo "SDMX_VERSION=$(cat VERSION)" >> ${GITHUB_ENV}

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3.0.1
        with:
          release: R2024a
          cache: true

      - name: Build and install toolbox
        uses: matlab-actions/run-command@v3
        with:
          command: >
            ver = getenv('SDMX_VERSION')
            cd("MATLAB");
            build(ver);
            matlab.addons.toolbox.installToolbox("MatSDMX.mltbx");

      - name: Run MATLAB tests
        uses: matlab-actions/run-tests@v3
        with:
          source-folder: MATLAB/files
          select-by-folder: MATLAB/files/test
          test-results-junit: test-results/matlab-results.xml

      - name: Upload MATLAB toolbox artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: matlab-toolbox
          path: MATLAB/MatSDMX.mltbx
          if-no-files-found: error
