name: MATLAB CI

on:
  workflow_run:
    workflows: ["JAVA CI"]
    types:
      - completed
    branches:
      - master
      - develop

permissions:
  contents: read
  actions: read

jobs:
  test-matlab:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download SDMX.jar
        uses: actions/download-artifact@v8.0.1
        with:
          name: sdmx-jar
          path: MATLAB/files/lib

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3.0.1
        with:
          release: R2024a

      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Build & Install matlab package
        run: |
          cd MATLAB
          matlab -nodisplay -nosplash -nodesktop -softwareopengl -batch "build('1.0.0')"
          matlab -nodisplay -r "matlab.addons.toolbox.installToolbox('MatSDMX.mltbx');"

      - name: Matlab test
        run: |
          cd MATLAB/files/test
          matlab -batch "result=runtests('testSDMX.m'); exit(any([result.Failed]));"
