name: R CI

on:
  workflow_run:
    workflows: ["JAVA CI"]
    types:
      - completed
    branches:
      - master
      - develop

permissions:
  contents: read
  actions: read

jobs:
  test-r:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Setup job
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SDMX JAR from JAVA CI
        uses: actions/download-artifact@v8.0.1
        with:
          name: SDMX.jar
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          path: RJSDMX/inst/java

      - name: Download VERSION from JAVA CI
        uses: actions/download-artifact@v8.0.1
        with:
          name: VERSION
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          path: .

      - name: Apply VERSION
        run: |
          SDMX_VERSION="$(cat VERSION)"
          sed -i 's/${r.style.version}/'"${VERSION}"'/' RJSDMX/DESCRIPTION
          
      - name: Setup tinytex for R manuals
        uses: r-lib/actions/setup-tinytex@v2
        
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: deps::./RJSDMX
          extra-packages: any::RUnit

      - name: Build R package
        run: |
          R CMD build ./RJSDMX
          TARBALL="$(find . -maxdepth 1 -type f -name 'RJSDMX*.tar.gz' -print -quit)"
          if [ -z ${TARBALL} ]; then exit 1; fi
          R CMD check --as-cran --no-tests "${TARBALL}"
          echo "TARBALL=${TARBALL}" >> "$GITHUB_ENV"
          
      - name: Run R Tests
        run: |
          R CMD INSTALL "${TARBALL}"
          Rscript -e "library(RUnit); library(RJSDMX); runTestFile('RJSDMX/R/test_automation/test.sdmx.r')"

      - name: Upload R package artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: cran-package
          path: ${{ env.TARBALL }}
          archive: false
          if-no-files-found: error
