
name: R CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-java:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        # Setup job
        - name: Set up JDK 11 for x64
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            architecture: x64
        - run: echo $JAVA_HOME

        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4.3.2'

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: deps::./RJSDMX
            extra-packages: any::RUnit

        - name: Testing
          run: |
            R CMD INSTALL ./RJSDMX && \
            Rscript -e "library(RUnit); library(RJSDMX); runTestFile('RJSDMX/R/test_automation/test.sdmx.r')"
